name: Terraform CICD Pipeline

on:
  workflow_dispatch:

jobs:
  terraform:
    name: 'Terraform Pipeline'
    runs-on: ubuntu-latest

    env:
      AWS_REGION: 'eu-west-1'
      TF_VERSION: '1.4.0'

    steps:
      - name: 'Checkout GitHub repository'
        uses: actions/checkout@v3

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: 'Terraform Init'
        run: terraform init

      - name: 'Terraform Format'
        run: terraform fmt

      - name: 'Terraform Validate'
        run: terraform validate

      - name: 'Terraform Plan'
        run: terraform plan -out=tfplan -var="db_password=${{ secrets.db_password }}"

      - name: 'Terraform Apply'
        run: terraform apply -auto-approve tfplan
